travis:
  secure:
    BINSTAR_TOKEN: C2sKUdqmdWFzplYrDnKooYmlt5/FhEHerf8USl9oG3MbTDu/f/eXMgDSrVeZ021uGqgjd1P2mnBOzk3fU8bwCsu2GKO+UghXC68gxKkRR6TxjEMEcgBBifrMGJdQEoxF1x+UF0dRfgR1TQtX2WEQec+xGwSkJ/XGX91/EVDZRdvqhp9411IT19fTW4t+8jGpiHbsYd9dPW0t1lE6jZ394qMtsUvqEiUbTEdfLwAxRgHIw/M434P0VE2yvs8F0PpHx5qDGYdiaWmRakMxOz0/VoPTzbaW+UqCBKkdwG+C8Re8VPBTIf+sB5fG8M8o7nJ+ee+H2QWAzrWd0+h+jvAPMO+haXcxv+CBdEiu9m28IYQIr1t6fS+KtQsWUArV6G+BzmfrGWsfR0vu1XgAaqlfn22hvRDVH6VY3oJ19ctiRE/6oeywKJdmEq1Uv3MOCfkmghTCWGpYvMAvUg7WnOoRhnmwdBAHGwWflAAxhpM7wyTAeQWT/Q6SJ9RmYij7fx4uu2y+f6B973VYoOZpahsJ277AIqvCi66CZKuNRmt0ztYM4bY6+dYsIe8K1n6fpr+lA5UsYbep1kEF+SJj4izjqcTGKrWwHQSSMLydBRQcYUf5nzjYw3eFPrkVvabejCD3j37Xy8oOiukw2yVC0LphrWcy/H5kk7UDMVAb99vftWg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
